<a href="https://colab.research.google.com/github/gerryfrank10/NLP/blob/main/part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
words = ['hello', 'world', 'i', 'am', 'gerald',
          'and', 'gerald', 'is', 'using', 'torch',
          'to', 'build', 'a', 'character', 'model',
          'also', 'giovanna', 'is', 'my', 'daughter',
          'and', 'she', 'is', 'very', 'cute', 'also',
          'my', 'wife', 'is', 'a', 'loving', 'person',
          'she','takes', 'care', 'of', 'me', 'and', 'our',
          'family','we', 'enjoy', 'spending', 'time', 'together',
          'for', 'some', 'reasons', 'i', 'need', 'to', 'query', 'this']

In [3]:
import string
chars = string.ascii_lowercase
stoi = {ch: i+1 for i, ch in enumerate(chars)}
stoi['.'] = 0
itos = {i: ch for ch, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [137]:
block_size = 3
X, Y = [], []

for w in words:
    print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '->', itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X, dtype=torch.int64)
Y = torch.tensor(Y, dtype=torch.int64)

hello
... -> h
..h -> e
.he -> l
hel -> l
ell -> o
llo -> .
world
... -> w
..w -> o
.wo -> r
wor -> l
orl -> d
rld -> .
i
... -> i
..i -> .
am
... -> a
..a -> m
.am -> .
gerald
... -> g
..g -> e
.ge -> r
ger -> a
era -> l
ral -> d
ald -> .
and
... -> a
..a -> n
.an -> d
and -> .
gerald
... -> g
..g -> e
.ge -> r
ger -> a
era -> l
ral -> d
ald -> .
is
... -> i
..i -> s
.is -> .
using
... -> u
..u -> s
.us -> i
usi -> n
sin -> g
ing -> .
torch
... -> t
..t -> o
.to -> r
tor -> c
orc -> h
rch -> .
to
... -> t
..t -> o
.to -> .
build
... -> b
..b -> u
.bu -> i
bui -> l
uil -> d
ild -> .
a
... -> a
..a -> .
character
... -> c
..c -> h
.ch -> a
cha -> r
har -> a
ara -> c
rac -> t
act -> e
cte -> r
ter -> .
model
... -> m
..m -> o
.mo -> d
mod -> e
ode -> l
del -> .
also
... -> a
..a -> l
.al -> s
als -> o
lso -> .
giovanna
... -> g
..g -> i
.gi -> o
gio -> v
iov -> a
ova -> n
van -> n
ann -> a
nna -> .
is
... -> i
..i -> s
.is -> .
my
... -> m
..m -> y
.my -> .
daughter
... -> d
..d -> a
.da

In [138]:
import torch.nn.functional as F
import torch.nn as nn

In [6]:
C = torch.randn((27, 2))

In [7]:
C[5], C[5].dtype

(tensor([ 0.6472, -1.1181]), torch.float32)

In [8]:
# 1 , 27 x 27, 2 = 1, 2
F.one_hot(torch.tensor(5), num_classes=27).float() @ C # We are typecasting to float to match the dtype of C

tensor([ 0.6472, -1.1181])

In [9]:
X.shape, Y.shape

(torch.Size([14, 3]), torch.Size([14]))

In [10]:
C[X]

tensor([[[-0.0096, -0.3447],
         [-0.0096, -0.3447],
         [-0.0096, -0.3447]],

        [[-0.0096, -0.3447],
         [-0.0096, -0.3447],
         [ 0.6169,  0.1482]],

        [[-0.0096, -0.3447],
         [ 0.6169,  0.1482],
         [ 0.6472, -1.1181]],

        [[ 0.6169,  0.1482],
         [ 0.6472, -1.1181],
         [ 0.0724, -1.9945]],

        [[ 0.6472, -1.1181],
         [ 0.0724, -1.9945],
         [ 0.0724, -1.9945]],

        [[ 0.0724, -1.9945],
         [ 0.0724, -1.9945],
         [ 1.7589,  0.8087]],

        [[-0.0096, -0.3447],
         [-0.0096, -0.3447],
         [-0.0096, -0.3447]],

        [[-0.0096, -0.3447],
         [-0.0096, -0.3447],
         [ 0.2100,  0.8273]],

        [[-0.0096, -0.3447],
         [ 0.2100,  0.8273],
         [ 1.7589,  0.8087]],

        [[ 0.2100,  0.8273],
         [ 1.7589,  0.8087],
         [-0.7421,  1.2301]],

        [[ 1.7589,  0.8087],
         [-0.7421,  1.2301],
         [ 0.0724, -1.9945]],

        [[-0.7421,  1

In [11]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  8],
        [ 0,  8,  5],
        [ 8,  5, 12],
        [ 5, 12, 12],
        [12, 12, 15],
        [ 0,  0,  0],
        [ 0,  0, 23],
        [ 0, 23, 15],
        [23, 15, 18],
        [15, 18, 12],
        [18, 12,  4],
        [ 0,  0,  0],
        [ 0,  0,  9]])

In [12]:
C[0], C[0], C[0], C[0], C[0], C[8]

(tensor([-0.0096, -0.3447]),
 tensor([-0.0096, -0.3447]),
 tensor([-0.0096, -0.3447]),
 tensor([-0.0096, -0.3447]),
 tensor([-0.0096, -0.3447]),
 tensor([0.6169, 0.1482]))

In [13]:
C[X].shape

torch.Size([14, 3, 2])

In [14]:
X[13, 2]

tensor(9)

In [15]:
C[X][13, 2]

tensor([ 0.0121, -1.3684])

In [16]:
C[9]

tensor([ 0.0121, -1.3684])

In [17]:
emb = C[X]  # (N, block_size, D)

In [18]:
w1 = torch.randn(size=(6, 100))
b1 = torch.randn(size=(100,))

In [19]:
# We can't do this emb @ w1 + b1 because the dimensions don't match
# We need to reshape emb to (N, block_size * D) to match w1
emb_reshaped = emb.view(emb.shape[0], -1)  # (N, block_size * D)
(emb_reshaped @ w1 + b1).shape  # (N, 100)

torch.Size([14, 100])

In [20]:
h = torch.tanh(emb_reshaped @ w1 + b1)  # (N, 100)
h.shape

torch.Size([14, 100])

In [21]:
W2 = torch.randn(size=(100, 27))
b2 = torch.randn(size=(27,))

In [22]:
logits = h @ W2 + b2  # (N, 27)

In [23]:
logits.shape

torch.Size([14, 27])

In [24]:
counts = logits.exp()

In [25]:
probs = counts / counts.sum(dim=1, keepdim=True)  # (N, 27)

In [26]:
probs[0].sum()

tensor(1.0000)

In [27]:
Y

tensor([ 8,  5, 12, 12, 15,  0, 23, 15, 18, 12,  4,  0,  9,  0])

In [28]:
probs.shape

torch.Size([14, 27])

In [29]:
probs[[0,1], Y[0]]  # Probability of the first character in the first word

tensor([7.4770e-10, 6.6980e-14])

In [30]:
probs[torch.arange(probs.shape[0]), Y] # probs[0].shape is 14 as with Y.shape = 14

tensor([7.4770e-10, 6.0842e-11, 3.2278e-05, 1.1914e-09, 9.8804e-08, 6.5523e-08,
        1.9243e-09, 3.0742e-12, 2.3060e-08, 1.3229e-06, 4.3239e-09, 4.5460e-09,
        1.6043e-06, 1.7268e-10])

In [31]:
loss = -probs[torch.arange(probs.shape[0]), Y].log().mean()
loss

tensor(18.5775)

## TODO

In [139]:
g = torch.Generator().manual_seed(42)
C = torch.randn((27, 2), generator=g)
W1 = torch.randn(size=(6,100), generator=g)
b1 = torch.randn(size=(100,), generator=g)
W2 = torch.randn(size=(100,27), generator=g)
b2 = torch.randn(size=(27,), generator=g)
parameters = [C, W1, b1, W2, b2]

In [140]:
sum(p.numel() for p in parameters)

3481

In [141]:
for p in parameters:
    p.requires_grad = True  # Enable gradient tracking

In [207]:
# Forward pass
for _ in range(1000):
    emb = C[X]
    h= torch.tanh(emb.view(emb.shape[0], -1) @ W1 + b1)
    logits = h @ W2 + b2
    loss = F.cross_entropy(logits, Y)
    print(loss.item())
    for p in parameters:
        p.grad = None
    loss.backward()
    #Update parameters
    for p in parameters:
        # print(p.grad)
        p.data += -0.1 * p.grad  # Gradient descent step

0.7322985529899597
0.7322971820831299
0.7322984337806702
0.7322970628738403
0.7322981953620911
0.7322967648506165
0.732297956943512
0.7322964668273926
0.7322977185249329
0.7322962284088135
0.7322974801063538
0.7322961091995239
0.7322973608970642
0.7322958111763
0.7322971820831299
0.7322956323623657
0.7322970032691956
0.7322955131530762
0.7322968244552612
0.7322952747344971
0.7322964072227478
0.732295036315918
0.7322962880134583
0.7322947978973389
0.7322961091995239
0.7322946190834045
0.7322958111763
0.7322943210601807
0.7322956919670105
0.7322940826416016
0.7322954535484314
0.7322938442230225
0.7322952151298523
0.7322937250137329
0.7322950959205627
0.7322935461997986
0.7322947978973389
0.7322933077812195
0.732294499874115
0.7322931289672852
0.7322943210601807
0.732292890548706
0.7322940826416016
0.7322927117347717
0.7322939038276672
0.7322924733161926
0.7322937846183777
0.7322921752929688
0.7322935461997986
0.7322919368743896
0.7322932481765747
0.7322918176651001
0.7322930097579956
0.7

In [171]:
values = logits.max(dim=1).indices
values

tensor([ 1,  5, 12, 12, 15,  0,  1, 15, 18, 12,  4,  0,  1, 19,  1, 14,  0,  1,
         5, 18,  1, 12,  4,  0,  1, 14,  4,  0,  1,  5, 18,  1, 12,  4,  0,  1,
        19,  0,  1, 19,  9, 14,  7,  0,  1, 15,  0,  3,  8,  0,  1, 15,  0,  1,
        21,  9, 12,  4,  0,  1, 14,  1,  8,  1, 18,  1,  3, 20,  5, 18,  0,  1,
        25,  4,  5, 12,  0,  1, 14, 19, 15,  0,  1,  5, 15, 22,  1, 14, 14,  1,
         0,  1, 19,  0,  1, 25,  0,  1,  1, 21,  7,  8, 20,  5, 18,  0,  1, 14,
         4,  0,  1,  8,  5,  0,  1, 19,  0,  1,  5, 18, 25,  0,  1,  8, 20,  5,
         0,  1, 14, 19, 15,  0,  1, 25,  0,  1, 15,  6,  5,  0,  1, 19,  0,  1,
        14,  1, 15, 22,  9, 14,  7,  0,  1,  5, 18, 19, 15, 14, 19,  1,  8,  5,
         0,  1, 15, 11,  5, 19,  0,  1,  8, 18,  5,  0,  1, 21,  0,  1, 25,  0,
         1, 14,  4,  0,  1, 21, 18,  0,  1, 15, 13,  9, 12, 25,  0,  1, 15,  0,
         1, 14, 10, 15, 25,  0,  1,  8,  5, 14,  4,  9, 14,  7,  0,  1, 15, 13,
         5,  0,  1, 15,  0,  5, 20,  8, 

In [208]:
values2 = logits.max(dim=1).indices
values2

tensor([ 1,  5, 12, 12, 15,  0,  1,  5, 18, 12,  4,  0,  1, 19,  1, 14,  0,  1,
         5, 18,  1, 12,  4,  0,  1, 14,  4,  0,  1,  5, 18,  1, 12,  4,  0,  1,
        19,  0,  1, 19,  9, 14,  7,  0,  1, 15,  0,  3,  8,  0,  1, 15,  0,  1,
        21,  9, 12,  4,  0,  1, 14,  1,  8,  1, 18,  1,  3, 20,  5, 18,  0,  1,
        25,  4,  5, 12,  0,  1, 14, 19, 15,  0,  1,  5, 15, 22,  1, 14, 14,  1,
         0,  1, 19,  0,  1, 25,  0,  1,  1, 21,  7,  8, 20,  5, 18,  0,  1, 14,
         4,  0,  1,  8,  5,  0,  1, 19,  0,  1,  5, 18, 25,  0,  1,  8, 20,  5,
         0,  1, 14, 19, 15,  0,  1, 25,  0,  1,  5,  6,  5,  0,  1, 19,  0,  1,
        14,  1, 15, 22,  9, 14,  7,  0,  1,  5, 18, 19, 15, 14, 19,  1,  8,  5,
         0,  1, 15, 11,  5, 19,  0,  1,  8, 18,  5,  0,  1, 21,  0,  1, 25,  0,
         1, 14,  4,  0,  1, 21, 18,  0,  1, 15, 13,  9, 12, 25,  0,  1,  5,  0,
         1, 14, 10, 15, 25,  0,  1,  8,  5, 14,  4,  9, 14,  7,  0,  1, 15, 13,
         5,  0,  1, 15,  0,  5, 20,  8, 

In [172]:
Y

tensor([ 8,  5, 12, 12, 15,  0, 23, 15, 18, 12,  4,  0,  9,  0,  1, 13,  0,  7,
         5, 18,  1, 12,  4,  0,  1, 14,  4,  0,  7,  5, 18,  1, 12,  4,  0,  9,
        19,  0, 21, 19,  9, 14,  7,  0, 20, 15, 18,  3,  8,  0, 20, 15,  0,  2,
        21,  9, 12,  4,  0,  1,  0,  3,  8,  1, 18,  1,  3, 20,  5, 18,  0, 13,
        15,  4,  5, 12,  0,  1, 12, 19, 15,  0,  7,  9, 15, 22,  1, 14, 14,  1,
         0,  9, 19,  0, 13, 25,  0,  4,  1, 21,  7,  8, 20,  5, 18,  0,  1, 14,
         4,  0, 19,  8,  5,  0,  9, 19,  0, 22,  5, 18, 25,  0,  3, 21, 20,  5,
         0,  1, 12, 19, 15,  0, 13, 25,  0, 23,  9,  6,  5,  0,  9, 19,  0,  1,
         0, 12, 15, 22,  9, 14,  7,  0, 16,  5, 18, 19, 15, 14,  0, 19,  8,  5,
         0, 20,  1, 11,  5, 19,  0,  3,  1, 18,  5,  0, 15,  6,  0, 13,  5,  0,
         1, 14,  4,  0, 15, 21, 18,  0,  6,  1, 13,  9, 12, 25,  0, 23,  5,  0,
         5, 14, 10, 15, 25,  0, 19, 16,  5, 14,  4,  9, 14,  7,  0, 20,  9, 13,
         5,  0, 20, 15,  7,  5, 20,  8, 

In [173]:
itos[values[0].item()], itos[Y[0].item()]

('a', 'h')

In [210]:
''.join([itos[i.item()] for i in values]), ''.join([itos[i.item()] for i in Y])

('aello.aerld.asan.aerald.and.aerald.as.asing.ao.ch.ao.auild.anaharacter.aydel.anso.aeovanna.as.ay.aaughter.and.ahe.as.aery.ahte.anso.ay.aefe.as.anaoving.aerson.ahe.aokes.ahre.au.ay.and.aur.aomily.ae.anjoy.ahending.aome.ao.ether.aor.ahme.aeason..asaeed.ao.auery.aois.',
 'hello.world.i.am.gerald.and.gerald.is.using.torch.to.build.a.character.model.also.giovanna.is.my.daughter.and.she.is.very.cute.also.my.wife.is.a.loving.person.she.takes.care.of.me.and.our.family.we.enjoy.spending.time.together.for.some.reasons.i.need.to.query.this.')

In [188]:
''.join([itos[i.item()] for i in values[10:20]]), ''.join([itos[i.item()] for i in Y[10:20]])

('d.asan.aer', 'd.i.am.ger')